name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - output

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the repository
        with:
          ref: output  # Make sure to use the 'output' branch

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push to output branch
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git push --force origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
